name: Feature Request
description: Suggest an idea for a new feature or enhancement.
labels:
  - feature
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I’m always frustrated when…
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
