name: Other Problem Report
description: Report an issue not directly related to a SID or STAR.
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Detailed steps to reproduce the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Describe the expected (correct) behaviour.
      placeholder: It should…
