name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install latest NPM
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set version from release tag
        run: npm version ${{ github.event.release.tag_name }} --git-tag-version=false

      - name: Generate
        run: npm run gen

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LTCC.txt
          path: LTCC.txt

      - name: Upload to release
        uses: cloudnode-pro/release-upload-asset@1.0.2
        with:
          gh-token: ${{ github.token }}
          files: LTCC.txt; type=text/plain
